### ISSUE TITLE
Hej, varsågod

### ISSUE THREAD

**Issue by dennan141** [ElinSjogren/hundklubben#2]
//checka om inloggning finns i localStorage?
  if(localStorage.inloggad){
    valkommenText();
    inloggning();
  } 
På rad 25; just nu kollar du om det finns en "localStorage.inloggad" och den ger sant oavsett om den innehåller texten "true" eller texten "false"
Du bör ändra den till if(localStorage.inloggad === "true"){ ...
så kommer det att funka sen :)

Anledningen är att localStorage endast kan spara Strings alltså inga siffror eller boolean så du måste kolla strängar (eller göra om dem men strunt i det :) )

**Comment by ElinSjogren** [comment]
Testat ändra nu :)
